services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./sql:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
      timeout: 5s
      retries: 5
    networks:
      - mytheresa-network

  api:
    build: .
    ports:
      - "8484:8484"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ENV: production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      HTTP_PORT: ${HTTP_PORT}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_SQL_DIR: ${POSTGRES_SQL_DIR}
      POSTGRES_HOST: ${POSTGRES_HOST}
    networks:
      - mytheresa-network

networks:
    mytheresa-network:
        driver: bridge

volumes:
    postgres_data:
        driver: local
    mytheresa-network:
        driver: bridge